### ISSUE TITLE
Support variant of Gpro

### ISSUE THREAD

**Issue by ShieldDev** [EmmanuelU/wild_kernel_lge_gproj#2]
EmmanuelU, please support for F310x, this is same F240x and E98x.
Specifications:
Chipset Qualcomm Snapdragon 600
CPU Quad-core 1.7 GHz Krait 300
GPU Adreno 320

Code name: omega (F310L), omegar (F310LR).
Thank you so much.

**Comment by EmmanuelU** [comment]
That is a different device, that is an Optimus GX not a GPro....you're going to have to get in contact with developers who have that device.

In the future, don't post feature requests on github issues page. I have my XDA thread for that: http://forum.xda-developers.com/optimus-g-pro/orig-development/kernel-wildkernel-build-1-featurlicous-t3069629
